#ifndef ENUM_COMPAT_H
#define ENUM_COMPAT_H

// The Android-ported source files use descriptive names, but the original
// enums.h uses numbered names. These aliases make both work.

// BGS level-specific flags
#define BGS_SPECIFIC_FLAG_WALKWAY_JIGGY_RESET              BGS_SPECIFIC_FLAG_2_WALKWAY_JIGGY_RESET
#define BGS_SPECIFIC_FLAG_WALKWAY_JIGGY_TIMER_RUNNING      BGS_SPECIFIC_FLAG_3_WALKWAY_JIGGY_TIMER_RUNNING
#define BGS_SPECIFIC_FLAG_WALKWAY_JIGGY                    BGS_SPECIFIC_FLAG_4_WALKWAY_JIGGY
#define BGS_SPECIFIC_FLAG_WALKWAY_JIGGY_SWITCH_PRESSED     BGS_SPECIFIC_FLAG_5_WALKWAY_JIGGY_SWITCH_PRESSED
#define BGS_SPECIFIC_FLAG_MAZE_JIGGY_SWITCH_PRESSED        BGS_SPECIFIC_FLAG_9_MAZE_JIGGY_SWITCH_PRESSED
#define BGS_SPECIFIC_FLAG_MAZE_JIGGY_RESET                 BGS_SPECIFIC_FLAG_B_MAZE_JIGGY_RESET
#define BGS_SPECIFIC_FLAG_MAZE_JIGGY_TIMER_RUNNING         BGS_SPECIFIC_FLAG_C_MAZE_JIGGY_TIMER_RUNNING
#define BGS_SPECIFIC_FLAG_MAZE_JIGGY                       BGS_SPECIFIC_FLAG_D_MAZE_JIGGY

#endif // ENUM_COMPAT_H

// Actor name aliases — Android source files use descriptive names
// that differ from the original decomp's numbered names
#define ACTOR_298_ZUBBA_DOOR    ACTOR_29C_ZUBBA_DOCILE
#define ACTOR_29A_ZUBBA_DOOR    ACTOR_29C_ZUBBA_DOCILE
