#ifndef ENUM_COMPAT_H
#define ENUM_COMPAT_H

// The Android-ported source files use descriptive names, but the original
// enums.h uses numbered names. These aliases make both work.

// BGS level-specific flags
#define BGS_SPECIFIC_FLAG_WALKWAY_JIGGY_RESET              BGS_SPECIFIC_FLAG_2_WALKWAY_JIGGY_RESET
#define BGS_SPECIFIC_FLAG_WALKWAY_JIGGY_TIMER_RUNNING      BGS_SPECIFIC_FLAG_3_WALKWAY_JIGGY_TIMER_RUNNING
#define BGS_SPECIFIC_FLAG_WALKWAY_JIGGY                    BGS_SPECIFIC_FLAG_4_WALKWAY_JIGGY
#define BGS_SPECIFIC_FLAG_WALKWAY_JIGGY_SWITCH_PRESSED     BGS_SPECIFIC_FLAG_5_WALKWAY_JIGGY_SWITCH_PRESSED
#define BGS_SPECIFIC_FLAG_MAZE_JIGGY_SWITCH_PRESSED        BGS_SPECIFIC_FLAG_9_MAZE_JIGGY_SWITCH_PRESSED
#define BGS_SPECIFIC_FLAG_MAZE_JIGGY_RESET                 BGS_SPECIFIC_FLAG_B_MAZE_JIGGY_RESET
#define BGS_SPECIFIC_FLAG_MAZE_JIGGY_TIMER_RUNNING         BGS_SPECIFIC_FLAG_C_MAZE_JIGGY_TIMER_RUNNING
#define BGS_SPECIFIC_FLAG_MAZE_JIGGY                       BGS_SPECIFIC_FLAG_D_MAZE_JIGGY

#endif // ENUM_COMPAT_H

// Actor name aliases — Android source files use descriptive names
// that differ from the original decomp's numbered names
#define ACTOR_298_ZUBBA_DOOR    ACTOR_29C_ZUBBA_DOCILE
#define ACTOR_29A_ZUBBA_DOOR    ACTOR_29C_ZUBBA_DOCILE

// CCW season bare-name aliases (used by Android-ported source files)
#define SPRING  CCW_SEASON_0_SPRING
#define SUMMER  CCW_SEASON_1_SUMMER
#define AUTUMN  CCW_SEASON_2_AUTUMN
#define WINTER  CCW_SEASON_3_WINTER

// Level-specific flag aliases
#define LEVEL_FLAG_25_CCW_UNKNOWN    LEVEL_FLAG_38_CCW_UNKNOWN

// Grublin animation aliases (Android port uses different names)
#define ASSET_62_ANIM_GRUBLIN_IDLE    ASSET_62_ANIM_GRUBLIN_IDLE_WALK
#define ASSET_63_ANIM_GRUBLIN_WALK    ASSET_63_ANIM_GRUBLIN_CHASE
#define ASSET_64_ANIM_GRUBLIN_JUMP    ASSET_64_ANIM_GRUBLIN_ALERT

#define ACTOR_175_MODEL_RUSTY_BUCKET_REAR_PROPELLER    ACTOR_175_RUSTY_BUCKET_REAR_PROPELLER

#define MARKER_184_RBB_EGG_TOLL    MARKER_182_RBB_EGG_TOLL
#define MARKER_183_RBB_EGG_TOLL    MARKER_182_RBB_EGG_TOLL

// SM vegetable actors
#define ACTOR_TOPPER_THE_CARROT_B    ACTOR_36F_TOPPER_THE_CARROT_B
#define ACTOR_BAWL_THE_ONION_B       ACTOR_36E_BAWL_THE_ONION_B
#define ACTOR_COLLYWOBBLE_B          ACTOR_36D_COLLYWOBBLE_B

// SM unknown
#define MARKER_1F0_SM_UNKNOWN        MARKER_1F5_UNKNOWN
#define ACTOR_3BD_SM_UNKNOWN         ACTOR_3BA_UNKNOWN
